title: Personal Notebook
author: Yarden
email: yarden_gur@yahoo.com
description: > # this means to ignore newlines until "show_exerpts:"
  This will serve me as a personal notebook where I'll write down my own guides for statistics and programming incase I'll need to refreshen my memory in the future.
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Yarden Gur
  tagline: Notebook
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  search: true # set to true to enable searchbar
  dark_mode: false # set to true to add dark mode toggle
  #portfolio_image:  "assets/Scan.png" # the path from the base directory of the site to the image to display (no / at the start)
  html_lang: "en" # set the lang attribute of the <html> tag for the pages. See here for a list of codes: https://www.w3schools.com/tags/ref_country_codes.asp

  # generate social links in footer
  social_links:
    twitter: yarden_gur
    github:  bm1125
    linkedIn: http://linkedin.com/in/yarden-gur-871426262/
    #rss: rss
    #dribbble: jekyll
    # flickr:   guryarden
    #instagram: jekyll
    #pinterest: jekyll
    #youtube: jekyll
    #facebook: jekyll
    #soundcloud: jekyll
    telegram: yardeng
    #gitlab: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: plainwhite
remote_theme: hydecorp/hydejack@v9
markdown: kramdown
plugins:
  - jekyll-seo-tag
#  - jekyll-feed
